apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ag-test
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  roles:
  - description: Github role based access
    groups:
    - AppGyver:appgyver-devops
    name: cluster-admin
    policies:
    - p, proj:ag-test:cluster-admin, applications, *, ag-test/*, allow
  sourceRepos:
  - https://github.com/pre/argocd-public-test
