apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lolcat-nginx
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  project: ag-test
  source:
    path: nginx
    targetRevision: main
    repoURL: https://github.com/pre/argocd-public-test
    plugin:
      name: kustomize-agenvsubst
      env:
      - name: AG_ENVSUBST_SOURCE
        value: envsubst/hello
      - name: AG_BUMP_VERSION
        value: "1"
      - name: AG_APP_NAMESPACE
        value: lolcats
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
